#eureka:
#  client:
#    register-with-eureka: false
#server:
#  port: 8222
#  spring:
#    application:
#      name: gateway
#    cloud:
#      gateway:
#        discovery:
#          locator:
#            enabled:
#        router:
#          -id: students
#          uri: http://localhost:8090
#        predicates:
#          - path=/api/v1/student/**
#        -id: school
#        uri: http://localhost:8070
#      predicates:
#        - path=/api/v1/school/**
#  management:
#    tracing:
#      sampling:
#        probability: 1.0
#
server:
  port: 8222

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: lb://students-service
          predicates:
            - Path=/api/v1/student/**
        - id: school
          uri: lb://school-service
          predicates:
            - Path=/api/v1/school/**
